### ISSUE TITLE
integrate with vue.js

### ISSUE THREAD

**Issue by 9585999** [qwtel/hy-push-state#3]
Hi, is there any way to integrate `hy-push-state.js` with `vue.js`?

**Comment by qwtel** [comment]
I don't know enough about vue to give a definitve answer. I know it would work with React, by just telling React to render the `hy-push-state` tag. 

It's not clear that the hy-push-state/vue combination makes a lot of sense though. I'm pretty sure vue has its own routing solution. hy-push-state is intended to make transitions between static (or server rendered) sites more dynamic.

**Comment by 9585999** [comment]
@qwtel Yes, indeed, the view has its own router `vue-router`.

But there are a number of reasons why I do not want to use it.

---

Actually the project itself on `laravel + vue`.

I included hy-push-state as follows: 

```js
import { HyPushState } from 'hy-push-state/src/vanilla'

function initHyPushState() {
    let element = document.getElementById('app')
    let pushStateEl = new HyPushState(element, {
        replaceIds: ['wrap-main'],
        scrollRestoration: true,
    })
}

Vue.nextTick(() => initHyPushState())

```

And in the end I thought that everything works, but it turned out that vue does not render the components on the pages on which the transition is performed:

![kapture 2018-07-13 at 11 50 01](https://user-images.githubusercontent.com/16165904/42682341-fe2d2c72-8692-11e8-9515-4f04f40b78d3.gif)

**Comment by qwtel** [comment]
I can't really go into detail here. I can only reiterate that it's probably not a good fit.
